workflows:
  expo_apk_debug_native:
    name: Expo Native Debug Build
    environment:
      node: 20
      java: 17
    scripts:
      - name: Set permission
        script: chmod +x index.sh
      - name: Install Expo CLI (README)
        script: |
          corepack disable || true
          npm i -g expo@latest
          expo --version
      - name: Build Debug Native (follow README)
        script: ./index.sh --native-android -p debug
    artifacts:
      - android/app/build/outputs/**/*.apk
      - builds/android/*.apk
