workflows:
  expo_native_android_debug:
    name: Expo Native Android (Debug)
    environment:
      node: 20
      java: 17
      vars:
        NODE_OPTIONS: --max-old-space-size=4096
    scripts:
      - name: Make index.sh executable
        script: chmod +x ./index.sh

      - name: Ensure Expo CLI (npm; avoid Yarn/corepack)
        script: |
          corepack disable || true
          npm i -g expo@latest
          expo --version

      - name: Install dependencies (npm)
        script: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: (Optional) Expo prebuild if missing
        script: |
          if [ ! -d android ]; then
            npx expo prebuild --platform android --no-install
          fi

      - name: Build Debug APK (Native)
        script: ./index.sh --native-android -p debug

    artifacts:
      - builds/android/*.apk
      - android/app/build/outputs/apk/debug/*.apk
