workflows:
  expo_native_android_debug:
    name: Expo Native Android (Debug)
    environment:
      node: 20
      java: 17
    scripts:
      - name: Make index.sh executable
        script: chmod +x ./index.sh
      - name: Build Debug APK (Native)
        script: ./index.sh --native-android -p debug
    artifacts:
      - builds/android/*.apk
      - android/app/build/outputs/apk/debug/*.apk
