workflows:
  android_apk_release:
    name: Android APK (assembleRelease)
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      node: 20
      java: 17
      groups:
        - android_keystore   # cipta group ini & simpan ANDROID_KEYSTORE_* jika mahu release signed
    scripts:
      - name: Papar struktur repo (debug)
        script: |
          pwd
          ls -la
          echo "--- tools/"
          [ -d tools ] && ls -la tools | head -n 50 || echo "tools/ tiada"
          echo "--- android/"
          [ -d android ] && ls -la android | head -n 50 || echo "android/ tiada"

      - name: Install Node deps
        script: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi
          node -v
          npm -v

      - name: (Opsyenal) Expo prebuild — skip bila android/ wujud
        script: |
          if [ ! -d android ] || [ ! -f android/gradlew ]; then
            npx --yes expo prebuild --platform android || true
          else
            echo "android/ sudah wujud — skip expo prebuild"
          fi

      - name: Wire tools ⇆ android (autopatch)
        script: |
          if [ -f tools/autopatch_tools_android.sh ]; then
            bash tools/autopatch_tools_android.sh
          else
            echo "autopatch_tools_android.sh tiada — terus build tanpa patch"
          fi

      - name: Build APK (Release)
        script: |
          cd android
          chmod +x ./gradlew || true
          ./gradlew --version
          ./gradlew assembleRelease --no-daemon --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab

  android_apk_debug:
    name: Android APK (assembleDebug - unsigned)
    max_build_duration: 120
    instance_type: linux_x2
    environment:
      node: 20
      java: 17
    scripts:
      - name: Install Node deps
        script: |
          if [ -f package-lock.json ]; then npm ci; else npm i; fi

      - name: (Opsyenal) Expo prebuild — skip bila android/ wujud
        script: |
          if [ ! -d android ] || [ ! -f android/gradlew ]; then
            npx --yes expo prebuild --platform android || true
          else
            echo "android/ sudah wujud — skip expo prebuild"
          fi

      - name: Build APK (Debug)
        script: |
          cd android
          chmod +x ./gradlew || true
          ./gradlew assembleDebug --no-daemon --stacktrace

    artifacts:
      - android/app/build/outputs/**/*.apk
